var menudata={children:[
{text:"Pagina Principale",url:"index.html"},
{text:"Namespace",url:"namespaces.html",children:[
{text:"Lista dei namespace",url:"namespaces.html"}]},
{text:"Classi",url:"annotated.html",children:[
{text:"Elenco dei tipi composti",url:"annotated.html"},
{text:"Indice dei tipi composti",url:"classes.html"},
{text:"Gerarchia delle classi",url:"inherits.html"},
{text:"Membri dei composti",url:"functions.html",children:[
{text:"Tutto",url:"functions.html",children:[
{text:"a",url:"functions.html#index_a"},
{text:"b",url:"functions.html#index_b"},
{text:"c",url:"functions.html#index_c"},
{text:"d",url:"functions.html#index_d"},
{text:"e",url:"functions.html#index_e"},
{text:"f",url:"functions.html#index_f"},
{text:"g",url:"functions.html#index_g"},
{text:"h",url:"functions.html#index_h"},
{text:"i",url:"functions.html#index_i"},
{text:"l",url:"functions.html#index_l"},
{text:"m",url:"functions.html#index_m"},
{text:"o",url:"functions.html#index_o"},
{text:"p",url:"functions.html#index_p"},
{text:"r",url:"functions.html#index_r"},
{text:"s",url:"functions.html#index_s"},
{text:"t",url:"functions.html#index_t"},
{text:"v",url:"functions.html#index_v"},
{text:"w",url:"functions.html#index_w"},
{text:"x",url:"functions.html#index_x"},
{text:"y",url:"functions.html#index_y"},
{text:"~",url:"functions.html#index_0x7e"}]},
{text:"Funzioni",url:"functions_func.html",children:[
{text:"c",url:"functions_func.html#index_c"},
{text:"d",url:"functions_func.html#index_d"},
{text:"e",url:"functions_func.html#index_e"},
{text:"f",url:"functions_func.html#index_f"},
{text:"g",url:"functions_func.html#index_g"},
{text:"h",url:"functions_func.html#index_h"},
{text:"i",url:"functions_func.html#index_i"},
{text:"l",url:"functions_func.html#index_l"},
{text:"m",url:"functions_func.html#index_m"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"},
{text:"t",url:"functions_func.html#index_t"},
{text:"v",url:"functions_func.html#index_v"},
{text:"w",url:"functions_func.html#index_w"},
{text:"x",url:"functions_func.html#index_x"},
{text:"y",url:"functions_func.html#index_y"},
{text:"~",url:"functions_func.html#index_0x7e"}]},
{text:"Variabili",url:"functions_vars.html"}]}]},
{text:"File",url:"files.html",children:[
{text:"Elenco dei file",url:"files.html"},
{text:"Elementi dei file",url:"globals.html",children:[
{text:"Tutto",url:"globals.html"},
{text:"Funzioni",url:"globals_func.html"},
{text:"Variabili",url:"globals_vars.html"},
{text:"Tipi enumerati (enum)",url:"globals_enum.html"},
{text:"Valori del tipo enumerato",url:"globals_eval.html"},
{text:"Definizioni",url:"globals_defs.html"}]}]}]}
